services:
  db:
    image: mysql:8.4.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:${DB_PORT}"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
      RAILS_ENV: development
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/zenn-gcp-rails
      - log-data:/zenn-gcp-rails/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  log-data:
  db-data:
